### ISSUE TITLE
Investigate moving collab, wiki, and account into more fully managed services

### ISSUE THREAD

**Issue by piet0024** [gctools-outilsgc/Issues#8]
Breakdown of everything involved for each of the apps

- [ ] [collab](https://github.com/gctools-outilsgc/gcconnex/issues/2470)
  *  web server - _apache + php5.6_         -> for now, build memcached into container image and use custom container azure web app service
     *    cache - _memcached_
     *  user uploaded file store - azure files
  *  DB - mysql / mariadb    - **not in k8s now**       -> move to managed mariadb / mysql
  * [ ]  [search - Solr](https://github.com/gctools-outilsgc/gcconnex/issues/2471)  - **not in k8s now**

  * Daily / weekly cron handling (can be just a simple command-line job)   ->  time triggered functions?
  * [ ] [DB backup jobs](https://github.com/gctools-outilsgc/Issues/issues/26)    -> the managed DBs do their own backups, might still be a good idea to do occasional sql dumps

- [ ] [wiki](https://github.com/gctools-outilsgc/gcpedia/issues/152)
 *  web server - _apache + php7+_          -> custom or default php7 container web app
 *  user uploaded file store - azure files
 *   DB - _mysql / mariadb_                 -> managed mariadb / mysql
 *   pdf rendering - msokk/electron-render-service (container), seems MW is switching back to mwlib for latest version?     -> custom container web app for now, seems there's a move back to mwlib happening so that may change things
  * [ ] [DB backup jobs](https://github.com/gctools-outilsgc/Issues/issues/26)

- [ ] [account](https://github.com/gctools-outilsgc/concierge/issues/246)
  *  web server - _python + django_         -> try default python container web app
     *   cache (only for recent failed logins) - _redis_        -> managed redis service most likely
     * branding / customization file store - azure files
  *  DB - _postgres_                        -> managed postgres
  
  * DB backup jobs

___

On top of that, will need:
 * Key vault for each app for secret and connection string storage

**Comment by LecCory** [comment]
Beginning some research on Azure Web apps to determine how the service scales and what options are required into order to build a highly available web service. I will document my findings and work on prototypes on my own tenant. 

@Phanoix - For collab front end if the plan going forward is to rebuild it in Angular we don't really need a webserver to serve the UI since page rendering happens in the client's browser and not from the server. We simply need a location to serve the static webfiles from. Azure Storage has a feature to web enable a storage container. Since we're not hosting a webserver, we don't have to worry about scaling and loadbalancing. The back end however would still need to have some planning to scale if we're still going to leverage Elgg, but that's where I'm going to spend time researching scaling options with Azure web apps.

**Comment by piet0024** [comment]
For the deliverable on this issue let's look at breaking this down into smaller Github issues to assign them in future sprints based on the investigation we are doing.

**Comment by Phanoix** [comment]
also to investigate / not forget to test as part of this:
 - gccollab and wiki - the apache + azure files smb + ubuntu 18+  file download issue
 -
